'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { ChevronLeft } from 'lucide-react';
import { useAuth } from '../../components/AuthProvider';
import { ProfilePill } from '../../components/ProfilePill';
import { QRScanner } from './QRScanner';
import { RecepcionForm } from './RecepcionForm';

type Tab = 'recepcion';

interface QRData {
  cod: string;
  palletsSent: number;
  bultosSent: number;
  guias: string[];
  driveFileId?: string;
}

type Step = 'scanner' | 'form' | 'done';

function parseQRData(raw: string): QRData | null {
  try {
    // Handle full URL (from QR codes generated by the system)
    let params: URLSearchParams;
    if (raw.startsWith('http')) {
      params = new URL(raw).searchParams;
    } else {
      params = new URLSearchParams(raw.includes('?') ? raw.split('?')[1] : `cod=${raw}`);
    }
    const cod = params.get('cod');
    if (!cod) return null;
    return {
      cod,
      palletsSent: parseInt(params.get('p') ?? '0', 10),
      bultosSent:  parseInt(params.get('b') ?? '0', 10),
      guias:       params.get('g') ? params.get('g')!.split(',').filter(Boolean) : [],
      driveFileId: params.get('drv') ?? undefined,
    };
  } catch {
    // Treat raw string as cod directly
    return { cod: raw, palletsSent: 0, bultosSent: 0, guias: [] };
  }
}

export function RecepcionTiendaScreen() {
  const router       = useRouter();
  const { profile, signOut } = useAuth();
  const [activeTab, setActiveTab] = useState<Tab>('recepcion');
  const [step,      setStep]      = useState<Step>('scanner');
  const [qrData,    setQrData]    = useState<QRData | null>(null);
  const [qrError,   setQrError]   = useState('');

  const TABS: { key: Tab; label: string }[] = [
    { key: 'recepcion', label: 'Recepción' },
  ];

  function handleQRDetected(raw: string) {
    const data = parseQRData(raw);
    if (!data) {
      setQrError('QR inválido. Intenta de nuevo o ingresa el código manualmente.');
      setStep('scanner');
      return;
    }
    setQrData(data);
    setQrError('');
    setStep('form');
  }

  function handleDone() {
    setStep('done');
  }

  function handleScanAnother() {
    setQrData(null);
    setQrError('');
    setStep('scanner');
  }

  return (
    <div style={{ minHeight: '100vh', background: '#F8FAFF', display: 'flex', flexDirection: 'column' }}>

      {/* Header */}
      <div style={{ background: '#1B2A6B', padding: '14px 16px', display: 'flex', alignItems: 'center', gap: 12, boxShadow: '0 2px 12px rgba(0,0,0,0.3)', flexShrink: 0 }}>
        <button onClick={() => router.push('/control-interno')}
          style={{
            width: 36, height: 36, flexShrink: 0,
            background: 'linear-gradient(145deg, rgba(255,255,255,0.12), rgba(255,255,255,0.06))',
            border: '1px solid rgba(255,255,255,0.15)',
            boxShadow: '0 2px 8px rgba(0,0,0,0.25), inset 0 1px 0 rgba(255,255,255,0.15)',
            borderRadius: '50%', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center',
          }}>
          <ChevronLeft size={18} color="rgba(255,255,255,0.85)" strokeWidth={2} />
        </button>
        <div style={{ flex: 1 }}>
          <div style={{ color: '#fff', fontWeight: 800, fontSize: 17, letterSpacing: '0.02em' }}>Tiendas / Recepción</div>
          {profile && (
            <div style={{ color: 'rgba(255,255,255,0.5)', fontSize: 11, marginTop: 1 }}>
              {profile.full_name ?? profile.id}
            </div>
          )}
        </div>
        <ProfilePill compact />
      </div>

      {/* Tabs */}
      <div style={{ display: 'flex', gap: 0, background: '#fff', borderBottom: '1px solid #E5E7EB', flexShrink: 0 }}>
        {TABS.map(tab => (
          <button key={tab.key} onClick={() => setActiveTab(tab.key)}
            style={{
              flex: 1, padding: '12px 0', border: 'none', cursor: 'pointer', fontSize: 14, fontWeight: 700,
              background: 'none',
              color: activeTab === tab.key ? '#1B2A6B' : '#9CA3AF',
              borderBottom: activeTab === tab.key ? '3px solid #1B2A6B' : '3px solid transparent',
              letterSpacing: '0.03em',
            }}>
            {tab.label}
          </button>
        ))}
      </div>

      {/* Content */}
      <div style={{ flex: 1, overflowY: 'auto' }}>

        {activeTab === 'recepcion' && (
          <>
            {step === 'scanner' && (
              <div style={{ padding: '20px 16px', display: 'flex', flexDirection: 'column', gap: 16 }}>
                <div style={{ textAlign: 'center' }}>
                  <p style={{ margin: '0 0 4px', fontSize: 16, fontWeight: 700, color: '#1F2937' }}>Escanear QR de tienda</p>
                  <p style={{ margin: 0, fontSize: 13, color: '#6B7280' }}>Apunta la cámara al código QR impreso en la etiqueta Zebra</p>
                </div>
                {qrError && (
                  <div style={{ background: '#FEF2F2', border: '1px solid #FECACA', borderRadius: 12, padding: '10px 14px', fontSize: 13, color: '#B91C1C', fontWeight: 500 }}>
                    ⚠️ {qrError}
                  </div>
                )}
                <div style={{ background: '#fff', borderRadius: 20, padding: 16, boxShadow: '0 2px 20px rgba(0,0,0,0.06)' }}>
                  <QRScanner onDetect={handleQRDetected} />
                </div>
              </div>
            )}

            {step === 'form' && qrData && (
              <RecepcionForm qrData={qrData} onDone={handleDone} onBack={handleScanAnother} />
            )}

            {step === 'done' && (
              <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', minHeight: 400, gap: 20, padding: 32, textAlign: 'center' }}>
                <div style={{ fontSize: 72, lineHeight: 1 }}>✅</div>
                <div>
                  <p style={{ margin: '0 0 6px', fontSize: 22, fontWeight: 800, color: '#111827' }}>¡Recepción confirmada!</p>
                  <p style={{ margin: 0, fontSize: 14, color: '#6B7280' }}>
                    {qrData ? `${qrData.cod} registrado correctamente` : 'Registro guardado'}
                  </p>
                </div>
                <button onClick={handleScanAnother}
                  style={{ background: '#1B2A6B', color: '#fff', border: 'none', borderRadius: 16, padding: '16px 32px', fontWeight: 700, fontSize: 16, cursor: 'pointer', boxShadow: '0 4px 20px rgba(27,42,107,0.35)' }}>
                  Escanear otra tienda
                </button>
              </div>
            )}
          </>
        )}
      </div>
    </div>
  );
}
